DEFRA/cyltfr

node/risk-app/server/models/search-view.js, node/risk-app/server/routes/search.js, node/risk-app/test/routes/search.js
https://eaflood.atlassian.net/browse/LTFRI-1108
=> Bug fix for all flood alerts being returned on a search

node/risk-app/client/sass/map-page.scss, node/risk-app/server/views/map.html, node/risk-app/server/views/risk.html
https://eaflood.atlassian.net/browse/LTFRI-1122
=> 'Data pause' content for the service

node/risk-app/client/sass/map-page.scss, node/risk-app/server/views/map.html, node/risk-app/server/views/risk.html
* Alter risk summary page to include data pause link
* Add pause message to map page
=> 'Data pause' content for the service (#249)

node/risk-admin/client/sass/_custom.scss, node/risk-admin/server/models/comment-edit.js, node/risk-admin/server/public/static/js/create-comment.js, node/risk-admin/server/public/static/js/edit-comment.js, node/risk-admin/server/public/static/js/partials/addFeature.js, node/risk-admin/server/routes/comment-edit.js, node/risk-admin/server/views/comment-edit.html
https://eaflood.atlassian.net/browse/LTFRI-1020
With the changes to the holding comments pages, the styling needs to be updated.
=> Add styling to holding comments

node/risk-admin/server/public/static/js/partials/addFeature.js, node/risk-admin/server/views/comment-edit.html
=> Merge Development to test

node/risk-admin/server/routes/comments-csv.js, node/risk-admin/server/routes/shp2json.js
https://eaflood.atlassian.net/browse/LTFRI-1110
=> Update download output on holding comments console

node/risk-app/.lintstagedrc, node/risk-app/package-lock.json, node/risk-app/package.json
The precommit hook for husky is not running during commits and needs to be fixed.
=> Fix for husky precommit not running on commit

node/risk-app/server/views/risk.html
https://eaflood.atlassian.net/browse/LTFRI-1151
Changing link to open in same tab for accessibility and data-journey link added added to the link to record user interaction.
=> Link opens page in same tab and data-journey-link added

node/risk-app/server/views/risk.html
Link opens page in same tab and data-journey-link added (#277)
https://eaflood.atlassian.net/browse/LTFRI-1151
Changed link to open in same tab for accessibility and data-journey link added added to the link to record user interaction.
=> Merge from development into test

node/risk-app/server/views/map.html, node/risk-app/server/views/risk.html
https://eaflood.atlassian.net/browse/LTFRI-1151
Update link on map page to stop opening in new tab, correct data-journey-click attribute
=> Bugfix - Correct data pause link

docs/release-notes/4.3.0/ltfri-4.3.0.txt, node/risk-app/package.json, node/risk-service/package.json
=> Release 4.3.0 prep

docs/release-notes/4.3.0/ltfri-4.3.0.txt, node/risk-app/package.json, node/risk-service/package.json
=> Release 4.3.0 prep (#289)

node/risk-app/server/config.js, node/risk-app/server/plugins/views.js, node/risk-app/server/public/static/js/cookies.js, node/risk-app/server/public/static/js/vendor/stageprompt.js, node/risk-app/server/views/layout.html, node/risk-app/server/views/risk.html
https://eaflood.atlassian.net/browse/LTFRI-1098
=> Set up google tag manager

node/risk-app/client/sass/rivers-and-sea.scss, node/risk-app/server/models/errors.json, node/risk-app/server/models/rivers-and-sea.js, node/risk-app/server/plugins/router.js, node/risk-app/server/routes/__tests__/rivers-and-sea.js, node/risk-app/server/routes/rivers-and-sea.js, node/risk-app/server/views/partials/rivers-sea.html, node/risk-app/server/views/rivers-and-sea.html
https://eaflood.atlassian.net/browse/LTFRI-1167
Prep update to add a rivers and the sea page, ready for NAFRA. This is a branch off of feature/ltfri-1163.
=> Update additional rivers and the sea page

node/risk-app/client/sass/rivers-and-sea.scss, node/risk-app/server/models/rivers-and-sea.js, node/risk-app/server/models/surface-water.js, node/risk-app/server/routes/__tests__/surface-water-disabled.js, node/risk-app/server/routes/__tests__/surface-water-enabled.js, node/risk-app/server/routes/surface-water.js, node/risk-app/server/views/partials/floodRatings.html, node/risk-app/server/views/rivers-and-sea.html, node/risk-app/server/views/surface-water.html
https://eaflood.atlassian.net/browse/LTFRI-1166
=> Update additional surface water page

node/risk-app/client/sass/rivers-and-sea.scss, node/risk-app/server/models/ground-water-view.js, node/risk-app/server/routes/__tests__/ground-water.spec.js, node/risk-app/server/routes/ground-water.js, node/risk-app/server/views/ground-water.html
https://eaflood.atlassian.net/browse/LTFRI-1168
The addition of a new groundwater and reservoir page.
=> Create additional groundwater and reservoir page

node/risk-app/client/sass/map-page.scss, node/risk-app/package-lock.json, node/risk-app/package.json, node/risk-service/package-lock.json, node/risk-service/package.json
https://eaflood.atlassian.net/browse/LTFRI-1213
=> Package updates

node/risk-app/Dockerfile, node/risk-service/Dockerfile
https://eaflood.atlassian.net/browse/LTFRI-1178
Defra has a image created specifically for our services which includes the Alpine base already.
=> Amend Docker to use Defra docker image rather than Node Alpine

node/risk-app/package.json
Updated version number to check Jenkins job running correctly.
=> Update version number for testing Jenkins

node/risk-app/server/views/risk-flagged.html
https://eaflood.atlassian.net/browse/LTFRI-1344
Users need to be able to print the summary page.
=> Print summary page not displaying

node/risk-app/client/sass/_map-controls.scss, node/risk-app/client/sass/map-page.scss
Map controls were off after previous bug fix and require fixing.
=> Quick bug fix for map controls

node/risk-app/server/views/risk-flagged.html
* Quick fix for holding comment title
=> Quick fix for holding comment title (#355)

node/risk-app/server/routes/search.js
https://eaflood.atlassian.net/browse/LTFRI-1387
=> Service shows an error when going direct to the search page

node/risk-app/server/routes/england-only.js, node/risk-app/server/routes/ground-water.js, node/risk-app/server/routes/map.js, node/risk-app/server/routes/postcode.js, node/risk-app/server/routes/risk.js, node/risk-app/server/routes/rivers-and-sea.js, node/risk-app/server/routes/search.js, node/risk-app/server/routes/surface-water.js, node/risk-app/server/services/__tests__/defineBackLink.spec.js, node/risk-app/server/services/defineBackLink.js, node/risk-app/server/views/england-only.html, node/risk-app/server/views/risk.html
https://eaflood.atlassian.net/jira/software/c/projects/LTFRI/boards/589?selectedIssue=LTFRI-1389
The exit map button currently takes the user back to the risk page, but it should take them back to the previous page.
=> Exiting the map should take you back to the correct page

docs/release-notes/4.5.1/ltfri-4.5.1.txt, docs/release-notes/4.5.2/ltfri-4.5.2.txt, docs/release-notes/4.5.3/ltfri-4.5.3.txt, docs/release-notes/4.5.4/ltfri-4.5.4.txt, node/risk-app/package.json, node/risk-service/package.json
=> Release 4.5.4 prep (#372)

node/risk-app/client/sass/_map-controls.scss, node/risk-app/client/sass/_map-key.scss, node/risk-app/client/sass/map-page.scss, node/risk-app/server/src/js/map-page/map-controls.js
https://eaflood.atlassian.net/browse/LTFRI-1223
When a user zooms level to 300% they are unable to scroll on the x-axis.
=> Side Scroll option not available

node/risk-app/server/views/accessibility-statement.html
https://eaflood.atlassian.net/browse/LTFRI-1495
Update the CYLTFR accessibility statement page.
=> Update accessibility statement
